package me.nik.anticheatbase.utils.custom;

public enum MaterialType {

    AIR("AIR", "CAVE_AIR", "VOID_AIR"),

    FENCE("OAK_FENCE", "SPRUCE_FENCE", "BIRCH_FENCE", "JUNGLE_FENCE", "ACACIA_FENCE",
            "DARK_OAK_FENCE", "CRIMSON_FENCE", "WARPED_FENCE", "NETHER_BRICK_FENCE", "OAK_FENCE_GATE",
            "SPRUCE_FENCE_GATE", "BIRCH_FENCE_GATE", "JUNGLE_FENCE_GATE", "ACACIA_FENCE_GATE",
            "DARK_OAK_FENCE_GATE", "CRIMSON_FENCE_GATE", "WARPED_FENCE_GATE", "FENCE", "IRON_FENCE",
            "FENCE_GATE", "NETHER_FENCE", "COBBLE_WALL", "COBBLESTONE_WALL", "MOSSY_COBBLESTONE_WALL",
            "BRICK_WALL", "PRISMARINE_WALL", "RED_SANDSTONE_WALL", "MOSSY_STONE_BRICK_WALL", "GRANITE_WALL",
            "STONE_BRICK_WALL", "NETHER_BRICK_WALL", "ANDESITE_WALL", "RED_NETHER_BRICK_WALL", "SANDSTONE_WALL",
            "END_STONE_BRICK_WALL", "DIORITE_WALL", "BLACKSTONE_WALL", "POLISHED_BLACKSTONE_WALL",
            "POLISHED_BLACKSTONE_BRICK_WALL", "COBBLED_DEEPSLATE_WALL", "POLISHED_DEEPSLATE_WALL"),

    SNOW("SNOW"),

    SHULKER("SHULKER_BOX", "WHITE_SHULKER_BOX", "ORANGE_SHULKER_BOX", "MAGENTA_SHULKER_BOX",
            "LIGHT_BLUE_SHULKER_BOX", "YELLOW_SHULKER_BOX", "LIME_SHULKER_BOX", "PINK_SHULKER_BOX",
            "GRAY_SHULKER_BOX", "LIGHT_GRAY_SHULKER_BOX", "CYAN_SHULKER_BOX", "PURPLE_SHULKER_BOX",
            "BLUE_SHULKER_BOX", "BROWN_SHULKER_BOX", "GREEN_SHULKER_BOX", "RED_SHULKER_BOX",
            "BLACK_SHULKER_BOX", "SILVER_SHULKER_BOX"),

    BED("BEDROCK", "WHITE_BED", "ORANGE_BED", "MAGENTA_BED", "LIGHT_BLUE_BED", "YELLOW_BED", "LIME_BED",
            "PINK_BED", "GRAY_BED", "LIGHT_GRAY_BED", "CYAN_BED", "PURPLE_BED", "BLUE_BED", "BROWN_BED", "GREEN_BED",
            "RED_BED", "BLACK_BED", "BED_BLOCK", "BED"),

    PISTON("PISTON", "STICKY_PISTON", "PISTON_HEAD", "MOVING_PISTON", "PISTON_STICKY_BASE", "PISTON_BASE",
            "PISTON_EXTENSION", "PISTON_MOVING_PIECE"),

    TRAPDOOR("IRON_TRAPDOOR", "OAK_TRAPDOOR", "SPRUCE_TRAPDOOR", "BIRCH_TRAPDOOR", "JUNGLE_TRAPDOOR",
            "ACACIA_TRAPDOOR", "DARK_OAK_TRAPDOOR", "CRIMSON_TRAPDOOR", "WARPED_TRAPDOOR", "TRAP_DOOR"),

    STAIRS("CUT_COPPER_STAIRS", "EXPOSED_CUT_COPPER_STAIRS", "WEATHERED_CUT_COPPER_STAIRS",
            "OXIDIZED_CUT_COPPER_STAIRS", "WAXED_CUT_COPPER_STAIRS", "WAXED_EXPOSED_CUT_COPPER_STAIRS",
            "WAXED_WEATHERED_CUT_COPPER_STAIRS", "WAXED_OXIDIZED_CUT_COPPER_STAIRS", "PURPUR_STAIRS",
            "OAK_STAIRS", "COBBLESTONE_STAIRS", "BRICK_STAIRS", "STONE_BRICK_STAIRS", "NETHER_BRICK_STAIRS",
            "SANDSTONE_STAIRS", "SPRUCE_STAIRS", "BIRCH_STAIRS", "JUNGLE_STAIRS", "CRIMSON_STAIRS", "WARPED_STAIRS",
            "QUARTZ_STAIRS", "ACACIA_STAIRS", "DARK_OAK_STAIRS", "PRISMARINE_STAIRS", "PRISMARINE_BRICK_STAIRS",
            "DARK_PRISMARINE_STAIRS", "RED_SANDSTONE_STAIRS", "POLISHED_GRANITE_STAIRS", "SMOOTH_RED_SANDSTONE_STAIRS",
            "MOSSY_STONE_BRICK_STAIRS", "POLISHED_DIORITE_STAIRS", "MOSSY_COBBLESTONE_STAIRS", "END_STONE_BRICK_STAIRS",
            "STONE_STAIRS", "SMOOTH_SANDSTONE_STAIRS", "SMOOTH_QUARTZ_STAIRS", "GRANITE_STAIRS", "ANDESITE_STAIRS",
            "RED_NETHER_BRICK_STAIRS", "POLISHED_ANDESITE_STAIRS", "DIORITE_STAIRS", "COBBLED_DEEPSLATE_STAIRS",
            "POLISHED_DEEPSLATE_STAIRS", "DEEPSLATE_BRICK_STAIRS", "DEEPSLATE_TILE_STAIRS", "BLACKSTONE_STAIRS",
            "POLISHED_BLACKSTONE_STAIRS", "POLISHED_BLACKSTONE_BRICK_STAIRS", "WOOD_STAIRS", "SMOOTH_STAIRS",
            "SPRUCE_WOOD_STAIRS", "BIRCH_WOOD_STAIRS", "JUNGLE_WOOD_STAIRS"),

    ICE("ICE", "FROSTED_ICE", "PACKED_ICE", "BLUE_ICE"),

    SLIME("SLIME_BLOCK"),

    WEB("WEB", "COBWEB"),

    CLIMBABLE("WEEPING_VINES", "TWISTING_VINES", "LADDER", "VINE", "WEEPING_VINES_PLANT",
            "TWISTING_VINES_PLANT", "CAVE_VINES", "CAVE_VINES_PLANT"),

    SOUL_BLOCK("SOUL_SAND", "SOUL_SOIL"),

    HONEY("HONEY_BLOCK"),

    BERRIES("SWEET_BERRY_BUSH"),

    SCAFFOLDING("SCAFFOLDING"),

    BUBBLE("BUBBLE_COLUMN"),

    LIQUID("WATER", "LAVA", "STATIONARY_WATER", "STATIONARY_LAVA"),

    HALF_BLOCK("CHORUS_PLANT", "CHORUS_FLOWER", "POPPED_CHORUS_FRUIT", "CHORUS_FRUIT_POPPED",
            "MOSS_CARPET", "WHITE_CARPET", "ORANGE_CARPET", "MAGENTA_CARPET", "LIGHT_BLUE_CARPET", "YELLOW_CARPET",
            "LIME_CARPET", "PINK_CARPET", "GRAY_CARPET", "LIGHT_GRAY_CARPET", "CYAN_CARPET", "PURPLE_CARPET",
            "BLUE_CARPET", "BROWN_CARPET", "GREEN_CARPET", "RED_CARPET", "BLACK_CARPET", "CARPET", "AZALEA_LEAVES",
            "FLOWERING_AZALEA_LEAVES", "AZALEA", "FLOWERING_AZALEA", "POTTED_AZALEA_BUSH",
            "POTTED_FLOWERING_AZALEA_BUSH", "BIG_DRIPLEAF", "SMALL_DRIPLEAF", "BIG_DRIPLEAF_STEM",
            "LILY_OF_THE_VALLEY", "LILY_PAD", "POTTED_LILY_OF_THE_VALLEY", "WATER_LILY", "END_ROD", "PLAYER_HEAD",
            "ZOMBIE_HEAD", "CREEPER_HEAD", "DRAGON_HEAD", "PISTON_HEAD", "ZOMBIE_WALL_HEAD", "PLAYER_WALL_HEAD",
            "CREEPER_WALL_HEAD", "DRAGON_WALL_HEAD", "SKELETON_SKULL", "WITHER_SKELETON_SKULL",
            "SKULL_BANNER_PATTERN", "SKELETON_WALL_SKULL", "WITHER_SKELETON_WALL_SKULL", "SKULL",
            "ANVIL", "CHIPPED_ANVIL", "DAMAGED_ANVIL", "STEP", "WOOD_STEP", "CUT_COPPER_SLAB",
            "EXPOSED_CUT_COPPER_SLAB", "WEATHERED_CUT_COPPER_SLAB", "OXIDIZED_CUT_COPPER_SLAB",
            "WAXED_CUT_COPPER_SLAB", "WAXED_EXPOSED_CUT_COPPER_SLAB", "WAXED_WEATHERED_CUT_COPPER_SLAB",
            "WAXED_OXIDIZED_CUT_COPPER_SLAB", "OAK_SLAB", "SPRUCE_SLAB", "BIRCH_SLAB", "JUNGLE_SLAB", "ACACIA_SLAB",
            "DARK_OAK_SLAB", "CRIMSON_SLAB", "WARPED_SLAB", "STONE_SLAB", "SMOOTH_STONE_SLAB", "SANDSTONE_SLAB",
            "CUT_SANDSTONE_SLAB", "PETRIFIED_OAK_SLAB", "COBBLESTONE_SLAB", "BRICK_SLAB", "STONE_BRICK_SLAB",
            "NETHER_BRICK_SLAB", "QUARTZ_SLAB", "RED_SANDSTONE_SLAB", "CUT_RED_SANDSTONE_SLAB", "PURPUR_SLAB",
            "PRISMARINE_SLAB", "PRISMARINE_BRICK_SLAB", "DARK_PRISMARINE_SLAB", "POLISHED_GRANITE_SLAB",
            "SMOOTH_RED_SANDSTONE_SLAB", "MOSSY_STONE_BRICK_SLAB", "POLISHED_DIORITE_SLAB", "MOSSY_COBBLESTONE_SLAB",
            "END_STONE_BRICK_SLAB", "SMOOTH_SANDSTONE_SLAB", "SMOOTH_QUARTZ_SLAB", "GRANITE_SLAB", "ANDESITE_SLAB",
            "RED_NETHER_BRICK_SLAB", "POLISHED_ANDESITE_SLAB", "DIORITE_SLAB", "COBBLED_DEEPSLATE_SLAB",
            "POLISHED_DEEPSLATE_SLAB", "DEEPSLATE_BRICK_SLAB", "DEEPSLATE_TILE_SLAB", "BLACKSTONE_SLAB",
            "POLISHED_BLACKSTONE_SLAB", "POLISHED_BLACKSTONE_BRICK_SLAB", "STONE_SLAB2", "PURPUR_SLAB",
            "ENDER_PORTAL_FRAME", "END_PORTAL_FRAME", "ENCHANTMENT_TABLE", "ENCHANTING_TABLE", "CAULDRON",
            "WATER_CAULDRON", "LAVA_CAULDRON", "POWDER_SNOW_CAULDRON", "COMPOSTER",
            "CHEST", "ENDER_CHEST", "TRAPPED_CHEST", "FARMLAND", "FLOWER_POT", "POTTED_OAK_SAPLING",
            "POTTED_SPRUCE_SAPLING", "POTTED_BIRCH_SAPLING", "POTTED_JUNGLE_SAPLING", "POTTED_ACACIA_SAPLING",
            "POTTED_DARK_OAK_SAPLING", "POTTED_FERN", "POTTED_DANDELION", "POTTED_POPPY", "POTTED_BLUE_ORCHID",
            "POTTED_ALLIUM", "POTTED_AZURE_BLUET", "POTTED_RED_TULIP", "POTTED_ORANGE_TULIP", "POTTED_WHITE_TULIP",
            "POTTED_PINK_TULIP", "POTTED_OXEYE_DAISY", "POTTED_CORNFLOWER", "POTTED_WITHER_ROSE", "POTTED_RED_MUSHROOM",
            "POTTED_BROWN_MUSHROOM", "POTTED_DEAD_BUSH", "POTTED_CACTUS", "POTTED_BAMBOO", "POTTED_CRIMSON_FUNGUS",
            "POTTED_WARPED_FUNGUS", "POTTED_CRIMSON_ROOTS", "POTTED_WARPED_ROOTS", "GRINDSTONE", "STONECUTTER",
            "POINTED_DRIPSTONE", "SEA_PICKLE", "SMALL_AMETHYST_BUD", "MEDIUM_AMETHYST_BUD", "LARGE_AMETHYST_BUD",
            "AMETHYST_CLUSTER", "CAMPFIRE", "SOUL_CAMPFIRE", "LANTERN", "SOUL_LANTERN", "CANDLE", "WHITE_CANDLE",
            "ORANGE_CANDLE", "MAGENTA_CANDLE", "LIGHT_BLUE_CANDLE", "YELLOW_CANDLE", "LIME_CANDLE", "PINK_CANDLE",
            "GRAY_CANDLE", "LIGHT_GRAY_CANDLE", "CYAN_CANDLE", "PURPLE_CANDLE", "BLUE_CANDLE", "BROWN_CANDLE",
            "GREEN_CANDLE", "RED_CANDLE", "BLACK_CANDLE", "CANDLE_CAKE", "WHITE_CANDLE_CAKE", "ORANGE_CANDLE_CAKE",
            "MAGENTA_CANDLE_CAKE", "LIGHT_BLUE_CANDLE_CAKE", "YELLOW_CANDLE_CAKE", "LIME_CANDLE_CAKE",
            "PINK_CANDLE_CAKE", "GRAY_CANDLE_CAKE", "LIGHT_GRAY_CANDLE_CAKE", "CYAN_CANDLE_CAKE", "PURPLE_CANDLE_CAKE",
            "BLUE_CANDLE_CAKE", "BROWN_CANDLE_CAKE", "GREEN_CANDLE_CAKE", "RED_CANDLE_CAKE", "BLACK_CANDLE_CAKE",
            "CAKE_BLOCK", "CAKE", "REPEATER", "COMPARATOR", "REDSTONE_COMPARATOR_OFF", "REDSTONE_COMPARATOR_ON",
            "REDSTONE_COMPARATOR", "DAYLIGHT_DETECTOR", "DAYLIGHT_DETECTOR_INVERTED", "LECTERN", "HOPPER",
            "IRON_DOOR", "OAK_DOOR", "SPRUCE_DOOR", "BIRCH_DOOR", "JUNGLE_DOOR", "ACACIA_DOOR",
            "DARK_OAK_DOOR", "CRIMSON_DOOR", "WARPED_DOOR", "WOODEN_DOOR", "IRON_DOOR_BLOCK", "WOOD_DOOR"),

    WATER_PLANT("KELP_PLANT", "SEAGRASS", "TALL_SEAGRASS");

    private final String[] values;

    MaterialType(String... values) {
        this.values = values;
    }

    public static boolean isMaterial(String value, MaterialType type) {
        /*
        Null checking since we're going to be using the "==" operator which is not null safe.
         */
        if (value == null) return false;

        /*
        Compare using "=="
        NOTE: This does improve perfomance by a L O T
        However this can ONLY be used in cases such as this (Materials)
        Where we're comparing string objects that never change no matter what (Applies to constant strings aswell).
         */
        for (String t : type.values) if (value == t) return true;

        return false;
    }
}